language: java

jdk: openjdk8

sudo: required

services:
  - docker

install:
  - docker pull mongo

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "josephthachilgeorge"
  
  cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - mvn -f spring-project/pom.xml clean verify -Pjacoco coveralls:report
   - mvn -f spring-project/pom.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report
   - mvn -f spring-project/pom.xml sonar:sonar -Dsonar.projectKey=JosephThachilGeorge_TDD
   - mvn -f spring-project/pom.xml verify -Pfailsafe
   - mvn -f spring-project/pom.xml verify -Pe2e
